---
all:
  children:
    masters:
      hosts:
        master:
          ansible_host: "13.60.36.207"
          ansible_user: "ubuntu"
          ansible_ssh_private_key_file: "/home/aitouaka/DevOps/projet/aws/keys/nb-key-pair.pem"
    nodes:
      hosts:
        worker1:
          ansible_host: "16.171.140.132"
          ansible_user: "ubuntu"
          ansible_ssh_private_key_file: "/home/aitouaka/DevOps/projet/aws/keys/nb-key-pair.pem"
        worker2:
          ansible_host: "13.51.146.207"
          ansible_user: "ubuntu"
          ansible_ssh_private_key_file: "/home/aitouaka/DevOps/projet/aws/keys/nb-key-pair.pem"