---
- name: "Pre-configuring Kubernetes Cluster"
  hosts: all
  become: yes
  roles:
    - common
    
- name: "Setting up Kubernetes Master Node"
  hosts: masters
  become: yes
  roles:
    - master

- name: "Joining Kubernetes Worker Nodes"
  hosts: nodes
  become: yes
  roles:
    - worker
